import {
  Repository,
  PullRequest,
  KPISummary,
  AgentBenchmark,
  BlockedTask,
  ToolOperationalImpact,
  ToolComparisonRow,
  RadarDataPoint,
  ThroughputBenchmark,
  AdoptionDistribution,
} from './types';

export const OPERATIONAL_IMPACTS: ToolOperationalImpact[] = [
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    impactPercent: 21,
    subtext: '482 active seats',
    icon: 'copilot',
    color: '#0ea5e9',
    badgeBg: 'bg-emerald-50 text-emerald-700',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    impactPercent: 8,
    subtext: '194 active seats',
    icon: 'cursor',
    color: '#1e293b',
    badgeBg: 'bg-emerald-50 text-emerald-700',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    impactPercent: 4,
    subtext: '120 active seats',
    icon: 'gemini',
    color: '#3b82f6',
    badgeBg: 'bg-emerald-50 text-emerald-700',
  },
  {
    id: 'sourcegraph',
    name: 'Sourcegraph',
    impactPercent: 1,
    subtext: '68 active seats',
    icon: 'sourcegraph',
    color: '#ea580c',
    badgeBg: 'bg-emerald-50 text-emerald-700',
  },
];

export const ADOPTION_DISTRIBUTION: AdoptionDistribution[] = [
  { category: '1 tool', percentage: 42, color: '#c4b5fd' },
  { category: '2 tools', percentage: 21, color: '#8b5cf6' },
  { category: '3+ tools', percentage: 7, color: '#4c1d95' },
  { category: 'No tools', percentage: 30, color: '#e2e8f0' },
];

export const THROUGHPUT_BENCHMARKS: ThroughputBenchmark[] = [
  { id: 'cursor', name: 'Cursor', icon: 'cursor', percentChange: -2, color: '#1e293b' },
  { id: 'gemini', name: 'Gemini', icon: 'gemini', percentChange: 10, color: '#3b82f6' },
  { id: 'copilot', name: 'GitHub Copilot', icon: 'copilot', percentChange: 12, color: '#0ea5e9' },
  { id: 'sourcegraph', name: 'Sourcegraph', icon: 'sourcegraph', percentChange: 23, color: '#ea580c' },
];

export const TOOL_COMPARISONS: ToolComparisonRow[] = [
  {
    id: 'copilot',
    name: 'GitHub Copilot',
    icon: 'copilot',
    usage: 80,
    velocity: -15,
    capacity: 8,
    sentiment: 54,
  },
  {
    id: 'cursor',
    name: 'Cursor',
    icon: 'cursor',
    usage: 60,
    velocity: -5,
    capacity: 6,
    sentiment: 85,
  },
  {
    id: 'gemini',
    name: 'Gemini',
    icon: 'gemini',
    usage: 40,
    velocity: -10,
    capacity: 11,
    sentiment: 82,
  },
  {
    id: 'sourcegraph',
    name: 'Sourcegraph',
    icon: 'sourcegraph',
    usage: 20,
    velocity: 0,
    capacity: 1,
    sentiment: 31,
  },
];

export const RADAR_DATA: RadarDataPoint[] = [
  { axis: 'Investment', copilot: 75, cursor: 55, gemini: 40, sourcegraph: 88 },
  { axis: 'KTLO', copilot: 68, cursor: 42, gemini: 50, sourcegraph: 78 },
  { axis: 'Review', copilot: 45, cursor: 78, gemini: 62, sourcegraph: 30 },
  { axis: 'Speed', copilot: 82, cursor: 88, gemini: 75, sourcegraph: 40 },
  { axis: 'Work', copilot: 70, cursor: 60, gemini: 84, sourcegraph: 35 },
  { axis: 'Say/Do', copilot: 65, cursor: 50, gemini: 60, sourcegraph: 45 },
  { axis: 'Delivery', copilot: 85, cursor: 72, gemini: 70, sourcegraph: 38 },
  { axis: 'Hit target', copilot: 78, cursor: 80, gemini: 58, sourcegraph: 42 },
  { axis: 'Roadmap', copilot: 60, cursor: 52, gemini: 45, sourcegraph: 50 },
];


export const INITIAL_REPOSITORIES: Repository[] = [
  {
    id: 101,
    url: 'https://github.com/acme-corp/api-gateway',
    license: 'MIT',
    full_name: 'acme-corp/api-gateway',
    is_forked: false,
    language: 'TypeScript',
    forks: 142,
    stars: 1280,
    pr_count: 148,
    avg_cycle_time_hours: 19.4,
    ai_adoption_rate: 68.2,
  },
  {
    id: 102,
    url: 'https://github.com/acme-corp/ml-inference-pipeline',
    license: 'Apache-2.0',
    full_name: 'acme-corp/ml-inference-pipeline',
    is_forked: false,
    language: 'Python',
    forks: 89,
    stars: 950,
    pr_count: 112,
    avg_cycle_time_hours: 22.1,
    ai_adoption_rate: 74.1,
  },
  {
    id: 103,
    url: 'https://github.com/acme-corp/data-lakehouse-engine',
    license: 'Apache-2.0',
    full_name: 'acme-corp/data-lakehouse-engine',
    is_forked: false,
    language: 'Rust',
    forks: 210,
    stars: 3410,
    pr_count: 94,
    avg_cycle_time_hours: 28.6,
    ai_adoption_rate: 52.3,
  },
  {
    id: 104,
    url: 'https://github.com/acme-corp/distributed-event-bus',
    license: 'BSD-3-Clause',
    full_name: 'acme-corp/distributed-event-bus',
    is_forked: false,
    language: 'Go',
    forks: 75,
    stars: 820,
    pr_count: 86,
    avg_cycle_time_hours: 18.2,
    ai_adoption_rate: 63.8,
  },
  {
    id: 105,
    url: 'https://github.com/acme-corp/payment-ledger-service',
    license: 'Proprietary',
    full_name: 'acme-corp/payment-ledger-service',
    is_forked: false,
    language: 'Java',
    forks: 34,
    stars: 410,
    pr_count: 60,
    avg_cycle_time_hours: 36.8,
    ai_adoption_rate: 41.5,
  },
];

export const INITIAL_KPIS: KPISummary = {
  total_prs: 500,
  merged_prs: 356,
  avg_cycle_time_hours: 21.8,
  avg_review_turnaround_hours: 3.4,
  ai_assisted_percentage: 63.8,
  throughput_per_week: 29.7,
  human_cycle_time_hours: 42.6,
  ai_cycle_time_hours: 18.2,
};

export const INITIAL_BENCHMARKS: AgentBenchmark[] = [
  {
    agent: 'cursor',
    label: 'Cursor AI',
    pr_count: 147,
    avg_cycle_time_hours: 16.9,
    avg_review_turnaround_hours: 2.3,
    merge_rate_percent: 81.6,
    color: '#7c3aed',
  },
  {
    agent: 'copilot',
    label: 'GitHub Copilot',
    pr_count: 172,
    avg_cycle_time_hours: 19.4,
    avg_review_turnaround_hours: 2.8,
    merge_rate_percent: 78.5,
    color: '#2563eb',
  },
  {
    agent: 'human',
    label: 'Human Baseline',
    pr_count: 181,
    avg_cycle_time_hours: 42.6,
    avg_review_turnaround_hours: 6.7,
    merge_rate_percent: 69.1,
    color: '#64748b',
  },
];

export const SAMPLE_PRS: PullRequest[] = [
  {
    id: 10101,
    number: 101,
    title: 'perf: optimize batch parquet serialization throughput by 35%',
    body: 'Utilized Polars memory mapping and zero-copy buffers to accelerate Parquet ingestion pipeline.',
    agent: 'cursor',
    user_id: 1001,
    user: 'sarah_chen',
    state: 'open',
    created_at: '2026-09-10T14:20:00Z',
    closed_at: null,
    merged_at: null,
    repo_id: 101,
    repo_url: 'https://github.com/acme-corp/api-gateway',
    html_url: 'https://github.com/acme-corp/api-gateway/pull/101',
    reviews: [
      {
        id: 501,
        pr_id: 10101,
        user: 'tech_lead_rachel',
        user_type: 'User',
        state: 'APPROVED',
        submitted_at: '2026-09-11T09:15:00Z',
        body: 'LGTM! Clean implementation and benchmarks show a measurable reduction in latency.',
      },
    ],
  },
  {
    id: 10102,
    number: 102,
    title: 'fix: resolve race condition in distributed lock acquisition',
    body: 'Add atomic Redis SETNX expiration safeguard to prevent split-brain during node rebalances.',
    agent: 'copilot',
    user_id: 1002,
    user: 'alex_novak',
    state: 'open',
    created_at: '2026-09-08T09:45:00Z',
    closed_at: null,
    merged_at: null,
    repo_id: 104,
    repo_url: 'https://github.com/acme-corp/distributed-event-bus',
    html_url: 'https://github.com/acme-corp/distributed-event-bus/pull/102',
    reviews: [
      {
        id: 502,
        pr_id: 10102,
        user: 'architect_ben',
        user_type: 'User',
        state: 'CHANGES_REQUESTED',
        submitted_at: '2026-09-09T11:00:00Z',
        body: 'High risk: potential deadlock when acquiring lock A then lock B, reversing standard cluster lock order.',
      },
    ],
  },
  {
    id: 10103,
    number: 103,
    title: 'feat: implement JWT auth middleware and RBAC role validation',
    body: 'Integrates token validation with cached public keys and custom middleware interceptors.',
    agent: 'cursor',
    user_id: 1003,
    user: 'priya_sharma',
    state: 'open',
    created_at: '2026-09-11T16:30:00Z',
    closed_at: null,
    merged_at: null,
    repo_id: 101,
    repo_url: 'https://github.com/acme-corp/api-gateway',
    html_url: 'https://github.com/acme-corp/api-gateway/pull/103',
    reviews: [
      {
        id: 503,
        pr_id: 10103,
        user: 'security_bot',
        user_type: 'Bot',
        state: 'COMMENTED',
        submitted_at: '2026-09-11T16:45:00Z',
        body: 'Static analysis check: verify clock skew tolerance is capped at 60 seconds.',
      },
    ],
  },
  {
    id: 10104,
    number: 104,
    title: 'chore: upgrade PostgreSQL connection pool settings and timeout handler',
    body: 'Configured max_overflow=20 and pool_pre_ping=True for resilient database reconnects.',
    agent: null,
    user_id: 1004,
    user: 'marcus_vance',
    state: 'open',
    created_at: '2026-09-12T04:10:00Z',
    closed_at: null,
    merged_at: null,
    repo_id: 105,
    repo_url: 'https://github.com/acme-corp/payment-ledger-service',
    html_url: 'https://github.com/acme-corp/payment-ledger-service/pull/104',
    reviews: [],
  },
  {
    id: 10105,
    number: 105,
    title: 'feat: Gemini 2.0 Flash embedding generator for documentation search',
    body: 'Added background batching worker for semantic document search with cosine similarity retrieval.',
    agent: 'copilot',
    user_id: 1005,
    user: 'elena_rostova',
    state: 'merged',
    created_at: '2026-09-07T10:00:00Z',
    closed_at: null,
    merged_at: '2026-09-08T03:30:00Z',
    repo_id: 102,
    repo_url: 'https://github.com/acme-corp/ml-inference-pipeline',
    html_url: 'https://github.com/acme-corp/ml-inference-pipeline/pull/105',
    cycle_time_hours: 17.5,
    reviews: [
      {
        id: 505,
        pr_id: 10105,
        user: 'tech_lead_rachel',
        user_type: 'User',
        state: 'APPROVED',
        submitted_at: '2026-09-08T02:00:00Z',
        body: 'LGTM! Great integration with google-generativeai package.',
      },
    ],
  },
  {
    id: 10106,
    number: 106,
    title: 'fix: memory leak during high-concurrency stream ingestion in Rust engine',
    body: 'Replaced unbounded channel with bounded crossbeam channel to regulate memory backpressure.',
    agent: null,
    user_id: 1006,
    user: 'david_kim',
    state: 'open',
    created_at: '2026-09-04T08:00:00Z',
    closed_at: null,
    merged_at: null,
    repo_id: 103,
    repo_url: 'https://github.com/acme-corp/data-lakehouse-engine',
    html_url: 'https://github.com/acme-corp/data-lakehouse-engine/pull/106',
    reviews: [
      {
        id: 506,
        pr_id: 10106,
        user: 'senior_dev_hugo',
        user_type: 'User',
        state: 'CHANGES_REQUESTED',
        submitted_at: '2026-09-06T14:00:00Z',
        body: 'Missing integration test under sustained pressure with 10k messages/sec.',
      },
    ],
  },
];

export const BLOCKED_TASKS_MOCK: BlockedTask[] = [
  {
    pr_id: 10106,
    title: 'fix: memory leak during high-concurrency stream ingestion in Rust engine',
    user: 'david_kim',
    repo_name: 'acme-corp/data-lakehouse-engine',
    reason: 'PR open for > 7 days without resolution (8.9 days)',
    days_blocked: 8.9,
    agent: null,
    created_at: '2026-09-04T08:00:00Z',
    blocker_comment: 'Missing integration test under sustained pressure with 10k messages/sec.',
  },
  {
    pr_id: 10102,
    title: 'fix: resolve race condition in distributed lock acquisition',
    user: 'alex_novak',
    repo_name: 'acme-corp/distributed-event-bus',
    reason: 'Changes requested > 3 days ago (3.8 days)',
    days_blocked: 3.8,
    agent: 'copilot',
    created_at: '2026-09-08T09:45:00Z',
    blocker_comment: 'High risk: potential deadlock when acquiring lock A then lock B, reversing standard cluster lock order.',
  },
];
